using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace TRPG.Core.Generators;

[Generator]
public sealed class NetworkingMethodGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MethodModel?> methods =
            context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax method &&
                    method.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetMethodModel(ctx))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(
            methods.Collect(),
            static (ctx, models) => Generate(ctx, models));
    }

    private static MethodModel? GetMethodModel(GeneratorSyntaxContext context)
    {
        var methodSyntax = (MethodDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(methodSyntax) is not IMethodSymbol methodSymbol)
            return null;

        foreach (var attribute in methodSymbol.GetAttributes())
        {
            var attributeClass = attribute.AttributeClass;

            if (attributeClass is null)
                continue;

            if (attributeClass.Name != "ReceiveAttribute" &&
                attributeClass.Name != "SendAttribute")
            {
                continue;
            }

            if (attributeClass.ContainingType?.Name != "NetworkingMethod")
                continue;

            if (attribute.ConstructorArguments.Length != 1)
                continue;

            string payloadExpression = ToEnumExpression(attribute.ConstructorArguments[0]);

            if (attributeClass.Name == "ReceiveAttribute")
            {
                if (methodSymbol.Parameters.Length != 1 ||
                    methodSymbol.Parameters[0].Type is not INamedTypeSymbol parameterType ||
                    parameterType.TypeArguments.Length != 1)
                {
                    return null;
                }

                return MethodModel.Receive(
                    payloadExpression,
                    methodSymbol.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    methodSymbol.Name,
                    parameterType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            return MethodModel.Send(
                methodSymbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : methodSymbol.ContainingNamespace.ToDisplayString(),
                methodSymbol.ContainingType.Name,
                methodSymbol.ContainingType.IsStatic,
                ToAccessibility(methodSymbol.DeclaredAccessibility),
                methodSymbol.IsStatic,
                methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                methodSymbol.ReturnsVoid,
                methodSymbol.Name,
                RemoveOnPrefix(methodSymbol.Name),
                methodSymbol.Parameters
                    .Select(static p => new ParameterModel(
                        p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        EscapeIdentifier(p.Name),
                        p.RefKind))
                    .ToImmutableArray());
        }

        return null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<MethodModel?> nullableModels)
    {
        var models = nullableModels
            .Where(static x => x is not null)
            .Select(static x => x!)
            .ToArray();

        GenerateReceiveMap(context, models.Where(static x => x.Kind == MethodKind.Receive).ToArray());
        GenerateSendWrappers(context, models.Where(static x => x.Kind == MethodKind.Send).ToArray());
    }

    private static void GenerateReceiveMap(SourceProductionContext context, MethodModel[] receiveMethods)
    {
        if (receiveMethods.Length == 0)
            return;

        var source = new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using TRPG.Protocol;");
        source.AppendLine();
        source.AppendLine("public delegate void PacketReceiveHandler<PayloadType>(in PacketReceiveContext<PayloadType> context)");
        source.AppendLine("    where PayloadType : struct, global::Google.FlatBuffers.IFlatbufferObject;");
        source.AppendLine();
        source.AppendLine("public static class PacketHandleMap");
        source.AppendLine("{");
        source.AppendLine("    public static readonly Dictionary<PayloadType, Delegate> receiveMap = new()");
        source.AppendLine("    {");

        foreach (var method in receiveMethods)
        {
            source.Append("        { ");
            source.Append(method.PayloadExpression);
            source.Append(", (PacketReceiveHandler<");
            source.Append(method.ReceivePayloadTypeName);
            source.Append(">)");
            source.Append(method.ContainingTypeFullName);
            source.Append('.');
            source.Append(method.OriginalMethodName);
            source.AppendLine(" },");
        }

        source.AppendLine("    };");
        source.AppendLine("}");

        context.AddSource("PacketHandleMap.generated.cs", source.ToString());
    }

    private static void GenerateSendWrappers(SourceProductionContext context, MethodModel[] sendMethods)
    {
        foreach (var group in sendMethods.GroupBy(static x => new
        {
            x.Namespace,
            x.ContainingTypeName,
            x.ContainingTypeIsStatic
        }))
        {
            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine();

            if (group.Key.Namespace is not null)
            {
                source.Append("namespace ");
                source.AppendLine(group.Key.Namespace);
                source.AppendLine("{");
            }

            string indent = group.Key.Namespace is null ? "" : "    ";
            string staticModifier = group.Key.ContainingTypeIsStatic ? "static " : "";

            source.Append(indent);
            source.Append("public ");
            source.Append(staticModifier);
            source.Append("partial class ");
            source.AppendLine(group.Key.ContainingTypeName);
            source.Append(indent);
            source.AppendLine("{");

            foreach (var method in group)
            {
                source.Append(indent);
                source.Append("    ");
                source.Append(method.Accessibility);
                source.Append(' ');

                if (method.MethodIsStatic)
                    source.Append("static ");

                source.Append(method.ReturnType);
                source.Append(' ');
                source.Append(method.GeneratedMethodName);
                source.Append('(');
                source.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
                source.AppendLine(")");

                source.Append(indent);
                source.AppendLine("    {");

                source.Append(indent);
                source.Append("        ");

                if (!method.ReturnsVoid)
                    source.Append("return ");

                source.Append(method.OriginalMethodName);
                source.Append('(');
                source.Append(string.Join(", ", method.Parameters.Select(FormatArgument)));
                source.AppendLine(");");

                source.Append(indent);
                source.AppendLine("    }");
                source.AppendLine();
            }

            source.Append(indent);
            source.AppendLine("}");

            if (group.Key.Namespace is not null)
                source.AppendLine("}");

            context.AddSource($"{group.Key.ContainingTypeName}.NetworkingMethod.generated.cs", source.ToString());
        }
    }

    private static string RemoveOnPrefix(string methodName)
    {
        if (methodName.Length > 2 && methodName.StartsWith("On"))
            return methodName.Substring(2);

        return methodName;
    }

    private static string FormatParameter(ParameterModel parameter)
    {
        string prefix = parameter.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };

        return prefix + parameter.TypeName + " " + parameter.Name;
    }

    private static string FormatArgument(ParameterModel parameter)
    {
        string prefix = parameter.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };

        return prefix + parameter.Name;
    }

    private static string ToEnumExpression(TypedConstant constant)
    {
        if (constant.Type is null)
            return "default";

        string typeName = constant.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        foreach (var member in constant.Type.GetMembers().OfType<IFieldSymbol>())
        {
            if (!member.HasConstantValue)
                continue;

            if (Equals(member.ConstantValue, constant.Value))
                return typeName + "." + member.Name;
        }

        return "(" + typeName + ")" + constant.Value;
    }

    private static string ToAccessibility(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "private"
        };
    }

    private static string EscapeIdentifier(string name)
    {
        if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ||
            SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None)
        {
            return "@" + name;
        }

        return name;
    }

    private enum MethodKind
    {
        Receive,
        Send
    }

    private sealed class MethodModel
    {
        private MethodModel(
            MethodKind kind,
            string payloadExpression,
            string? @namespace,
            string containingTypeName,
            bool containingTypeIsStatic,
            string containingTypeFullName,
            string accessibility,
            bool methodIsStatic,
            string returnType,
            bool returnsVoid,
            string originalMethodName,
            string generatedMethodName,
            string receivePayloadTypeName,
            ImmutableArray<ParameterModel> parameters)
        {
            Kind = kind;
            PayloadExpression = payloadExpression;
            Namespace = @namespace;
            ContainingTypeName = containingTypeName;
            ContainingTypeIsStatic = containingTypeIsStatic;
            ContainingTypeFullName = containingTypeFullName;
            Accessibility = accessibility;
            MethodIsStatic = methodIsStatic;
            ReturnType = returnType;
            ReturnsVoid = returnsVoid;
            OriginalMethodName = originalMethodName;
            GeneratedMethodName = generatedMethodName;
            ReceivePayloadTypeName = receivePayloadTypeName;
            Parameters = parameters;
        }

        public MethodKind Kind { get; }
        public string PayloadExpression { get; }
        public string? Namespace { get; }
        public string ContainingTypeName { get; }
        public bool ContainingTypeIsStatic { get; }
        public string ContainingTypeFullName { get; }
        public string Accessibility { get; }
        public bool MethodIsStatic { get; }
        public string ReturnType { get; }
        public bool ReturnsVoid { get; }
        public string OriginalMethodName { get; }
        public string GeneratedMethodName { get; }
        public string ReceivePayloadTypeName { get; }
        public ImmutableArray<ParameterModel> Parameters { get; }

        public static MethodModel Receive(
            string payloadExpression,
            string containingTypeFullName,
            string originalMethodName,
            string receivePayloadTypeName)
        {
            return new MethodModel(
                MethodKind.Receive,
                payloadExpression,
                null,
                "",
                false,
                containingTypeFullName,
                "",
                true,
                "void",
                true,
                originalMethodName,
                originalMethodName,
                receivePayloadTypeName,
                ImmutableArray<ParameterModel>.Empty);
        }

        public static MethodModel Send(
            string? @namespace,
            string containingTypeName,
            bool containingTypeIsStatic,
            string accessibility,
            bool methodIsStatic,
            string returnType,
            bool returnsVoid,
            string originalMethodName,
            string generatedMethodName,
            ImmutableArray<ParameterModel> parameters)
        {
            return new MethodModel(
                MethodKind.Send,
                "",
                @namespace,
                containingTypeName,
                containingTypeIsStatic,
                "",
                accessibility,
                methodIsStatic,
                returnType,
                returnsVoid,
                originalMethodName,
                generatedMethodName,
                "",
                parameters);
        }
    }

    private readonly struct ParameterModel
    {
        public ParameterModel(string typeName, string name, RefKind refKind)
        {
            TypeName = typeName;
            Name = name;
            RefKind = refKind;
        }

        public string TypeName { get; }
        public string Name { get; }
        public RefKind RefKind { get; }
    }
}
